name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.ubi --tag quay.io/chenj/razeedash-api:1.5.1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: quay.io/chenj
        username: ${{secrets['quayUser']}}
        password: ${{secrets['quayPassword']}}  
    - name: Push Docker Image
      run: docker push quay.io/chenj/razeedash-api:1.5.1